<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EdithistorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('edithistories')->insert([
            [
                'id' => 1,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 1,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
            ],
            [
                'id' => 2,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 2,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
            ],
            [
                'id' => 3,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 3,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
            ],
            [
                'id' => 4,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 4,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
            ],
            [
                'id' => 5,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 5,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
            ],
            [
                'id' => 6,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 6,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
            ],
            [
                'id' => 7,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 7,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
            ],
            [
                'id' => 8,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 8,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
            ],
            [
                'id' => 9,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 9,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:03:00'),
            ],
            [
                'id' => 10,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 10,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
            ],
            [
                'id' => 11,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 11,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
            ],
            [
                'id' => 12,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 12,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
            ],
            [
                'id' => 13,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 13,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
            ],
            [
                'id' => 14,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 14,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
            ],
            [
                'id' => 15,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 15,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
            ],
            [
                'id' => 16,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 16,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
            ],
            [
                'id' => 17,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 17,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
            ],
            [
                'id' => 18,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 18,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
            ],
            [
                'id' => 19,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 19,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:04:00'),
            ],
            [
                'id' => 20,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 20,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
            ],
            [
                'id' => 21,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 21,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
            ],
            [
                'id' => 22,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 22,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
            ],
            [
                'id' => 23,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 23,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
            ],
            [
                'id' => 24,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 24,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
            ],
            [
                'id' => 25,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 25,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
            ],
            [
                'id' => 26,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 26,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
            ],
            [
                'id' => 27,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 27,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
            ],
            [
                'id' => 28,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 28,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
            ],
            [
                'id' => 29,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 29,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:05:00'),
            ],
            [
                'id' => 30,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 30,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
            ],
            [
                'id' => 31,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 31,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
            ],
            [
                'id' => 32,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 32,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
            ],
            [
                'id' => 33,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 33,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
            ],
            [
                'id' => 34,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 34,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
            ],
            [
                'id' => 35,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 35,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
            ],
            [
                'id' => 36,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 36,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
            ],
            [
                'id' => 37,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 37,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
            ],
            [
                'id' => 38,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 38,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
            ],
            [
                'id' => 39,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 39,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:06:00'),
            ],
            [
                'id' => 40,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 40,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
            ],
            [
                'id' => 41,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 41,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
            ],
            [
                'id' => 42,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 42,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
            ],
            [
                'id' => 43,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 43,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
            ],
            [
                'id' => 44,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 44,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
            ],
            [
                'id' => 45,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 45,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
            ],
            [
                'id' => 46,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 46,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
            ],
            [
                'id' => 47,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 47,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
            ],
            [
                'id' => 48,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 48,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
            ],
            [
                'id' => 49,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 49,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
            ],
            [
                'id' => 50,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 50,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
            ],
            [
                'id' => 51,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 51,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id' => 52,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 52,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id' => 53,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 53,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id' => 54,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 54,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id' => 55,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 55,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id' => 56,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 56,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id' => 57,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 57,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id' => 58,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 58,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id' => 59,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 59,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id' => 60,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 60,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id' => 61,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 61,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id' => 62,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 62,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id' => 63,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 63,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id' => 64,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 64,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id' => 65,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 65,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id' => 66,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 66,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id' => 67,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 67,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id' => 68,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 68,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id' => 69,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 69,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id' => 70,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 70,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id' => 71,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 71,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
            ],
            [
                'id' => 72,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 72,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
            ],
            [
                'id' => 73,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 73,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
            ],
            [
                'id' => 74,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 74,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
            ],
            [
                'id' => 75,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 75,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
            ],
            [
                'id' => 76,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 76,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
            ],
            [
                'id' => 77,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 77,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
            ],
            [
                'id' => 78,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 78,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
            ],
            [
                'id' => 79,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 79,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
            ],
            [
                'id' => 80,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 80,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
            ],
            [
                'id' => 81,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 81,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
            ],
            [
                'id' => 82,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 82,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
            ],
            [
                'id' => 83,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 83,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
            ],
            [
                'id' => 84,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 84,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
            ],
            [
                'id' => 85,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 85,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
            ],
            [
                'id' => 86,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 86,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
            ],
            [
                'id' => 87,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 87,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
            ],
            [
                'id' => 88,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 88,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
            ],
            [
                'id' => 89,
                'edit_mode' => 'normal',
                'operation_type' => 'store',
                'item_id' => 89,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:11:00'),
            ],
            [
                'id' => 90,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 1,
                'edited_field' => 'remarks',
                'old_value' => '256GBモデル',
                'new_value' => '256GBモデル
        アップデート済み',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '9',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/10 10:56:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/10 10:56:00'),
            ],
            [
                'id' => 91,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 1,
                'edited_field' => 'acquisition_source',
                'old_value' => 'Amazon',
                'new_value' => '楽天市場',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/25 8:32:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/25 8:32:00'),
            ],
            [
                'id' => 92,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 2,
                'edited_field' => 'remarks',
                'old_value' => NULL,
                'new_value' => '修理中です',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '9',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/18 13:54:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/18 13:54:00'),
            ],
            [
                'id' => 93,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 3,
                'edited_field' => 'storage_location_id',
                'old_value' => '1',
                'new_value' => '2',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '5',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/01 10:16:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/01 10:16:00'),
            ],
            [
                'id' => 94,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 3,
                'edited_field' => 'price',
                'old_value' => '80000',
                'new_value' => '83000',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/18 14:51:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/18 14:51:00'),
            ],
            [
                'id' => 95,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 4,
                'edited_field' => 'manufacturer',
                'old_value' => 'ASUS',
                'new_value' => 'Dell',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/25 15:06:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/25 15:06:00'),
            ],
            [
                'id' => 96,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 4,
                'edited_field' => 'location_of_use_id',
                'old_value' => '1',
                'new_value' => '2',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '5',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/25 11:11:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/25 11:11:00'),
            ],
            [
                'id' => 97,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 5,
                'edited_field' => 'end_user',
                'old_value' => '山本',
                'new_value' => '神谷',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '4',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/27 13:22:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/27 13:22:00'),
            ],
            [
                'id' => 98,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 7,
                'edited_field' => 'manufacturer',
                'old_value' => 'Acer',
                'new_value' => 'Lenovo',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/18 14:46:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/18 14:46:00'),
            ],
            [
                'id' => 99,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 8,
                'edited_field' => 'acquisition_source',
                'old_value' => '楽天市場',
                'new_value' => 'ビックカメラ',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 8:41:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 8:41:00'),
            ],
            [
                'id' => 100,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 9,
                'edited_field' => 'storage_location_id',
                'old_value' => '2',
                'new_value' => '3',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '6',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/29 11:51:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/29 11:51:00'),
            ],
            [
                'id' => 101,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 10,
                'edited_field' => 'remarks',
                'old_value' => NULL,
                'new_value' => '修理に出しています。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '9',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/28 10:26:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/28 10:26:00'),
            ],
            [
                'id' => 102,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 12,
                'edited_field' => 'remarks',
                'old_value' => '動画編集用',
                'new_value' => '動画編集用
        Adobeのソフトをインストールしました',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '9',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/14 11:16:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/14 11:16:00'),
            ],
            [
                'id' => 103,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 13,
                'edited_field' => 'end_user',
                'old_value' => '内田',
                'new_value' => '木村',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '4',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/23 15:47:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/23 15:47:00'),
            ],
            [
                'id' => 104,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 13,
                'edited_field' => 'remarks',
                'old_value' => 'イラスト用',
                'new_value' => 'イラスト用
        不安定になったため、初期化しました。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '9',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/22 13:31:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/22 13:31:00'),
            ],
            [
                'id' => 105,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 15,
                'edited_field' => 'manufacturer',
                'old_value' => 'HP',
                'new_value' => 'Samsung',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/19 8:21:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/19 8:21:00'),
            ],
            [
                'id' => 106,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 19,
                'edited_field' => 'end_user',
                'old_value' => '山本',
                'new_value' => '神谷',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '4',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/27 13:24:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/27 13:24:00'),
            ],
            [
                'id' => 107,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 20,
                'edited_field' => 'remarks',
                'old_value' => NULL,
                'new_value' => '調子が悪いので代わりの新しいマウスが必要です。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/29 12:51:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/29 12:51:00'),
            ],
            [
                'id' => 108,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 21,
                'edited_field' => 'acquisition_source',
                'old_value' => 'ヨドバシカメラ',
                'new_value' => 'ビックカメラ',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 10:36:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 10:36:00'),
            ],
            [
                'id' => 109,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 24,
                'edited_field' => 'price',
                'old_value' => '1500',
                'new_value' => '1450',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/29 8:49:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/29 8:49:00'),
            ],
            [
                'id' => 110,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 26,
                'edited_field' => 'manufacturer',
                'old_value' => 'Elecom',
                'new_value' => 'Dell',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/25 9:12:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/25 9:12:00'),
            ],
            [
                'id' => 111,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 27,
                'edited_field' => 'end_user',
                'old_value' => NULL,
                'new_value' => '木村',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '4',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/23 15:47:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/23 15:47:00'),
            ],
            [
                'id' => 112,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 29,
                'edited_field' => 'end_user',
                'old_value' => '内田',
                'new_value' => '木村',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '4',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/23 15:47:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/23 15:47:00'),
            ],
            [
                'id' => 113,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 30,
                'edited_field' => 'remarks',
                'old_value' => NULL,
                'new_value' => '名刺カードに印刷可能です。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/12 9:14:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/12 9:14:00'),
            ],
            [
                'id' => 114,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 31,
                'edited_field' => 'remarks',
                'old_value' => '月額',
                'new_value' => '月額
        有線LANケーブルが必要です。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/08 13:56:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/08 13:56:00'),
            ],
            [
                'id' => 115,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 35,
                'edited_field' => 'price',
                'old_value' => '5000',
                'new_value' => '5100',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/30 9:57:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/30 9:57:00'),
            ],
            [
                'id' => 116,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 36,
                'edited_field' => 'remarks',
                'old_value' => NULL,
                'new_value' => '脚がぐらつくので返品交換してもらう必要がある。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 11:29:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 11:29:00'),
            ],
            [
                'id' => 117,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 37,
                'edited_field' => 'manufacturer',
                'old_value' => NULL,
                'new_value' => 'プラス',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/31 15:49:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/31 15:49:00'),
            ],
            [
                'id' => 118,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 38,
                'edited_field' => 'manufacturer',
                'old_value' => NULL,
                'new_value' => 'プラス',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/31 15:49:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/31 15:49:00'),
            ],
            [
                'id' => 119,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 39,
                'edited_field' => 'price',
                'old_value' => '15100',
                'new_value' => '15300',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/25 10:12:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/25 10:12:00'),
            ],
            [
                'id' => 120,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 40,
                'edited_field' => 'remarks',
                'old_value' => NULL,
                'new_value' => '単三電池4本使用',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/20 12:15:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/20 12:15:00'),
            ],
            [
                'id' => 121,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 42,
                'edited_field' => 'location_of_use_id',
                'old_value' => '3',
                'new_value' => '1',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '5',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/25 10:22:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/25 10:22:00'),
            ],
            [
                'id' => 122,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 46,
                'edited_field' => 'remarks',
                'old_value' => NULL,
                'new_value' => '「コロコロクリーナー替え」が別に登録してあります。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/12 9:56:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/12 9:56:00'),
            ],
            [
                'id' => 123,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 47,
                'edited_field' => 'remarks',
                'old_value' => '年額制',
                'new_value' => '年額制
        PC5台で使用出来ます。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 13:18:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 13:18:00'),
            ],
            [
                'id' => 124,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 48,
                'edited_field' => 'remarks',
                'old_value' => '年額制',
                'new_value' => '年額制
        PC1台で使用出来ます。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/08 15:21:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/08 15:21:00'),
            ],
            [
                'id' => 125,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 49,
                'edited_field' => 'manufacturer',
                'old_value' => NULL,
                'new_value' => 'Makita',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/18 13:45:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/18 13:45:00'),
            ],
            [
                'id' => 126,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 52,
                'edited_field' => 'name',
                'old_value' => 'ボールペン',
                'new_value' => 'ボールペン（黒）',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/08 14:45:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/08 14:45:00'),
            ],
            [
                'id' => 127,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 53,
                'edited_field' => 'manufacturer',
                'old_value' => NULL,
                'new_value' => 'ぺんてる',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/18 14:27:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/18 14:27:00'),
            ],
            [
                'id' => 128,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 54,
                'edited_field' => 'manufacturer',
                'old_value' => NULL,
                'new_value' => 'ぺんてる',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/01 9:35:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/01 9:35:00'),
            ],
            [
                'id' => 129,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 55,
                'edited_field' => 'manufacturer',
                'old_value' => NULL,
                'new_value' => 'ぺんてる',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/30 15:27:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/30 15:27:00'),
            ],
            [
                'id' => 130,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 56,
                'edited_field' => 'manufacturer',
                'old_value' => NULL,
                'new_value' => 'ぺんてる',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/18 14:47:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/18 14:47:00'),
            ],
            [
                'id' => 131,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 57,
                'edited_field' => 'manufacturer',
                'old_value' => NULL,
                'new_value' => 'サンワダイレクト',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/20 13:18:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/20 13:18:00'),
            ],
            [
                'id' => 132,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 62,
                'edited_field' => 'remarks',
                'old_value' => '20本パック',
                'new_value' => '20本パック
        注意：使い終わったら、ビニールテープで絶縁してください。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/25 13:32:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/25 13:32:00'),
            ],
            [
                'id' => 133,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 63,
                'edited_field' => 'remarks',
                'old_value' => '12本入り',
                'new_value' => '12本入り
        注意：使い終わったら、ビニールテープで絶縁してください。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/25 12:08:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/25 12:08:00'),
            ],
            [
                'id' => 134,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 64,
                'edited_field' => 'remarks',
                'old_value' => '6パック',
                'new_value' => '6パック
        使い過ぎないように周知する',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 9:31:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 9:31:00'),
            ],
            [
                'id' => 135,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 73,
                'edited_field' => 'price',
                'old_value' => '2000',
                'new_value' => '1900',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/30 15:47:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/30 15:47:00'),
            ],
            [
                'id' => 136,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 73,
                'edited_field' => 'remarks',
                'old_value' => '30本入り
        賞味期限あり',
                'new_value' => '30本入り
        賞味期限あり
        廃棄予定日が来たら廃棄してください。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/14 13:34:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/14 13:34:00'),
            ],
            [
                'id' => 137,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 79,
                'edited_field' => 'manufacturer',
                'old_value' => NULL,
                'new_value' => 'Panasonic',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/25 11:14:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/25 11:14:00'),
            ],
            [
                'id' => 138,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 80,
                'edited_field' => 'manufacturer',
                'old_value' => NULL,
                'new_value' => 'Sharp',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/18 15:21:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/18 15:21:00'),
            ],
            [
                'id' => 139,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 81,
                'edited_field' => 'price',
                'old_value' => '15000',
                'new_value' => '14000',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/25 9:47:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/25 9:47:00'),
            ],
            [
                'id' => 140,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 84,
                'edited_field' => 'remarks',
                'old_value' => '備え付け、点検が必要',
                'new_value' => '備え付け、点検が必要
        定期的に点検が必要です。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 9:35:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 9:35:00'),
            ],
            [
                'id' => 141,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 85,
                'edited_field' => 'remarks',
                'old_value' => '備え付け、点検が必要',
                'new_value' => '備え付け、点検が必要
        定期的に点検が必要です。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 9:35:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 9:35:00'),
            ],
            [
                'id' => 142,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 86,
                'edited_field' => 'remarks',
                'old_value' => '備え付け、点検が必要',
                'new_value' => '備え付け、点検が必要
        定期的に点検が必要です。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 9:35:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 9:35:00'),
            ],
            [
                'id' => 143,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 87,
                'edited_field' => 'remarks',
                'old_value' => NULL,
                'new_value' => '定期的に点検が必要です。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 9:40:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 9:40:00'),
            ],
            [
                'id' => 144,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 88,
                'edited_field' => 'price',
                'old_value' => '4800',
                'new_value' => '4500',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '2',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 14:29:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 14:29:00'),
            ],
            [
                'id' => 145,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 88,
                'edited_field' => 'remarks',
                'old_value' => '500ml×24本',
                'new_value' => '500ml×24本
        消費期限が近づいたら、新しいものを購入してください。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 10:17:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 10:17:00'),
            ],
            [
                'id' => 146,
                'edit_mode' => 'normal',
                'operation_type' => 'update',
                'item_id' => 89,
                'edited_field' => 'remarks',
                'old_value' => NULL,
                'new_value' => '定期的に点検が必要です。',
                'edit_user' => '管理者大川',
                'edit_reason_id' => '1',
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 9:47:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 9:47:00'),
            ],
            [
                'id' => 147,
                'edit_mode' => 'normal',
                'operation_type' => 'inspection',
                'item_id' => 89,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/20 15:50:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/20 15:50:00'),
            ],
            [
                'id' => 148,
                'edit_mode' => 'normal',
                'operation_type' => 'soft_delete',
                'item_id' => 11,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 15:04:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 15:04:00'),
            ],
            [
                'id' => 149,
                'edit_mode' => 'normal',
                'operation_type' => 'soft_delete',
                'item_id' => 26,
                'edited_field' => NULL,
                'old_value' => NULL,
                'new_value' => NULL,
                'edit_user' => '管理者大川',
                'edit_reason_id' => NULL,
                'edit_reason_text' => NULL,
                'created_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 15:05:00'),
                'updated_at' => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 15:05:00'),
            ],
        ]);
    }
}
