<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Category;
use Carbon\Carbon;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $startDate = Carbon::create(2023, 4, 1, 8, 0, 0);
        $endDate = Carbon::create(2024, 7, 31, 18, 0, 0);

        DB::table('items')->insert([
            [
                'name' => 'ペーパータオル',
                'management_id' => 'CO-1000',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル2',
                'management_id' => 'CO-1002',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル3',
                'management_id' => 'CO-1003',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル',
                'management_id' => 'CO-1000',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル2',
                'management_id' => 'CO-1002',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル3',
                'management_id' => 'CO-1003',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル',
                'management_id' => 'CO-1000',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル2',
                'management_id' => 'CO-1002',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル3',
                'management_id' => 'CO-1003',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル',
                'management_id' => 'CO-1000',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル2',
                'management_id' => 'CO-1002',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル3',
                'management_id' => 'CO-1003',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル',
                'management_id' => 'CO-1000',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル2',
                'management_id' => 'CO-1002',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル3',
                'management_id' => 'CO-1003',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル',
                'management_id' => 'CO-1000',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル2',
                'management_id' => 'CO-1002',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            // ここから生成したデータ
            [
                'name' => 'タブレット',
                'management_id' => 'IT-5522',
                'category_id' => 2,
                'image1' => '20240305_101844_PDmKPhAucM.jpeg',
                'stock' => 1,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 10,
                'storage_location_id' => 10,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => 49800,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'Apple',
                'product_number' => 'MK2N3J/A',
                'remarks' => '256GBモデル',
                'qrcode' => 'QR_20240305_132543_KDPv6VqxCx.jpeg',
                'created_at' => '2024-03-19 09:55:00'
            ],
            [
                'name' => 'ノートパソコン1',
                'management_id' => 'IT-5623',
                'category_id' => 2,
                'image1' => '20240305_110304_D5C8AUNeoI.jpeg',
                'stock' => 1,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 1,
                'storage_location_id' => 1,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => 80000,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'ASUS',
                'product_number' => 'VivoBook-2023',
                'remarks' => '',
                'qrcode' => 'QR_20240305_121236_46oAp7A7ES.jpeg',
                'created_at' => '2024-03-10 09:28:00'
            ],
            [
                'name' => 'ノートパソコン2',
                'management_id' => 'IT-5166',
                'category_id' => 2,
                'image1' => '20240305_172409_F3PggKx9DF.jpeg',
                'stock' => 1,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 1,
                'storage_location_id' => 1,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => 80000,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'ASUS',
                'product_number' => 'VivoBook-2023',
                'remarks' => '',
                'qrcode' => 'QR_20240305_134802_DiTZftbTEZ.jpeg',
                'created_at' => '2024-03-19 09:01:00'
            ],
            [
                'name' => 'ノートパソコン3',
                'management_id' => 'IT-4181',
                'category_id' => 2,
                'image1' => '20240305_164620_nK8UE41lq7.jpeg',
                'stock' => 1,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 1,
                'storage_location_id' => 1,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => 80000,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'ASUS',
                'product_number' => 'VivoBook-2023',
                'remarks' => '',
                'qrcode' => 'QR_20240305_134534_oyZxsqtLvE.jpeg',
                'created_at' => '2024-03-13 18:32:00'
            ],
            [
                'name' => 'ノートパソコン4',
                'management_id' => 'IT-4643',
                'category_id' => 2,
                'image1' => '20240305_100354_0LspmB73Oe.jpeg',
                'stock' => 1,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 1,
                'storage_location_id' => 1,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => 80000,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'ASUS',
                'product_number' => 'VivoBook-2023',
                'remarks' => '',
                'qrcode' => 'QR_20240305_105749_NLO5PPspvv.jpeg',
                'created_at' => '2024-03-17 17:40:00'
            ],
            [
                'name' => 'ノートパソコン5',
                'management_id' => 'IT-3427',
                'category_id' => 2,
                'image1' => '20240305_162759_O1GVbm643J.jpeg',
                'stock' => 1,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 2,
                'storage_location_id' => 2,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => 80000,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'ASUS',
                'product_number' => 'VivoBook-2023',
                'remarks' => '',
                'qrcode' => 'QR_20240305_114943_3NWiWMjnID.jpeg',
                'created_at' => '2024-03-19 11:29:00'
            ],
            [
                'name' => 'ノートパソコン6',
                'management_id' => 'IT-1500',
                'category_id' => 2,
                'image1' => '20240305_164005_TgnrSSZVno.jpeg',
                'stock' => 1,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 2,
                'storage_location_id' => 2,
                'acquisition_method_id' => 1,
                'acquisition_source' => '楽天市場',
                'price' => 75000,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'Acer',
                'product_number' => 'Spectre-2023',
                'remarks' => '',
                'qrcode' => 'QR_20240305_145038_aLe8vXehpC.jpeg',
                'created_at' => '2024-03-15 09:25:00'
            ],
            [
                'name' => 'ノートパソコン7',
                'management_id' => 'IT-3194',
                'category_id' => 2,
                'image1' => '20240305_112818_v5jHQ2oVYV.jpeg',
                'stock' => 1,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 2,
                'storage_location_id' => 2,
                'acquisition_method_id' => 1,
                'acquisition_source' => '楽天市場',
                'price' => 75000,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'Acer',
                'product_number' => 'Spectre-2023',
                'remarks' => '',
                'qrcode' => 'QR_20240305_145320_HavWZubsfK.jpeg',
                'created_at' => '2024/3/17  13:25:30'
            ],
            [
                'name' => 'ノートパソコン8',
                'management_id' => 'IT-9811',
                'category_id' => 2,
                'image1' => '20240305_173717_s1Fk6HyN9T.jpeg',
                'stock' => 1,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 2,
                'storage_location_id' => 2,
                'acquisition_method_id' => 1,
                'acquisition_source' => '楽天市場',
                'price' => 75000,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'Acer',
                'product_number' => 'Spectre-2023',
                'remarks' => '',
                'qrcode' => 'QR_20240305_100558_RmT0TxKSEe.jpeg',
                'created_at' => '2024-03-08 14:29:00'
            ],
            [
                'name' => 'ノートパソコン9',
                'management_id' => 'IT-1548',
                'category_id' => 2,
                'image1' => '20240305_113142_iqhuaZm2KE.jpeg',
                'stock' => 1,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 2,
                'end_user' => '',
                'location_of_use_id' => 10,
                'storage_location_id' => 10,
                'acquisition_method_id' => 1,
                'acquisition_source' => '楽天市場',
                'price' => 75000,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'Acer',
                'product_number' => 'Spectre-2023',
                'remarks' => '',
                'qrcode' => 'QR_20240305_123501_TIUvm7zilL.jpeg',
                'created_at' => '2024-03-18 12:18:00'
            ],
            [
                'name' => 'ノートパソコン10',
                'management_id' => 'IT-4512',
                'category_id' => 2,
                'image1' => '20240305_102811_vFUsIWmvaX.jpeg',
                'stock' => 1,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 2,
                'end_user' => '',
                'location_of_use_id' => 10,
                'storage_location_id' => 10,
                'acquisition_method_id' => 1,
                'acquisition_source' => '楽天市場',
                'price' => 75000,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'Acer',
                'product_number' => 'Spectre-2023',
                'remarks' => '壊れたため、廃棄予定',
                'qrcode' => 'QR_20240305_171936_lvsqvPifjR.jpeg',
                'created_at' => '2024-03-07 13:13:00'
            ],
            [
                'name' => 'デスクトップパソコン1',
                'management_id' => 'IT-4284',
                'category_id' => 2,
                'image1' => '20240305_092253_ZF9ctRNm7s.jpeg',
                'stock' => 1,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 1,
                'storage_location_id' => 1,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'ビックカメラ',
                'price' => 100000,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'HP',
                'product_number' => 'ThinkCentre-2023',
                'remarks' => '動画編集用',
                'qrcode' => 'QR_20240305_122158_gkcBXIoJMX.jpeg',
                'created_at' => '2024-03-10 17:28:00'
            ],
            [
                'name' => 'デスクトップパソコン2',
                'management_id' => 'IT-5409',
                'category_id' => 2,
                'image1' => '20240305_153238_kqeDzsaW1H.jpeg',
                'stock' => 1,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 1,
                'storage_location_id' => 1,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'ビックカメラ',
                'price' => 100000,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'HP',
                'product_number' => 'ThinkCentre-2023',
                'remarks' => 'イラスト用',
                'qrcode' => 'QR_20240305_083642_baUrNC2Cct.jpeg',
                'created_at' => '2024-03-15 16:36:00'
            ],
            [
                'name' => 'モニター1',
                'management_id' => 'IT-2400',
                'category_id' => 2,
                'image1' => '20240305_174839_haZAQUv6m7.jpeg',
                'stock' => 0,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 1,
                'storage_location_id' => 1,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'ビックカメラ',
                'price' => 16000,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'HP',
                'product_number' => '64W18AA',
                'remarks' => '24型',
                'qrcode' => 'QR_20240305_154912_d1zZcVPyhh.jpeg',
                'created_at' => '2024-03-07 16:12:00'
            ],
            [
                'name' => 'モニター2',
                'management_id' => 'IT-5270',
                'category_id' => 2,
                'image1' => '20240305_083843_PkUb98mhJX.jpeg',
                'stock' => 0,
                'unit_id' => 5,
                'minimum_stock' => 0,
                'notification' => false,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 1,
                'storage_location_id' => 1,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'ビックカメラ',
                'price' => 16000,
                'date_of_acquisition' => '2024-03-05',
                'manufacturer' => 'HP',
                'product_number' => '64W18AA',
                'remarks' => '24型',
                'qrcode' => 'QR_20240305_140542_PDR7UoWWUN.jpeg',
                'created_at' => '2024-03-05 08:47:00'
            ],
        ]);
    }

    private function randomDateTime($startDate, $endDate)
    {
        $randomTimestamp = rand($startDate->timestamp, $endDate->timestamp);
        $randomDateTime = Carbon::createFromTimestamp($randomTimestamp);

        // 時間を8:00～18:00の範囲に設定
        $randomHour = rand(8, 18);
        $randomDateTime->setTime($randomHour, rand(0, 59), rand(0, 59));

        return $randomDateTime;
    }

}
