<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Category;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('items')->insert([
            [
                'name' => 'ペーパータオル',
                'category_id' => 2,
                'image_path1' => 'sample1.jpg',
                'image_path2' => 'sample4.jpg',
                'image_path3' => 'sample5.jpg',
                'stocks' => '10',
                'minimum_stock' => '2',
                'usage_status' => '使用中',
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_category' => '購入',
                'where_to_buy' => 'Amazon',
                'price' => '500',
                'product_number' => '8001',
                'manufacturer' => 'エリエール',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'inspection_schedule' => null,
                'disposal_schedule' => null,
                'remarks' => '',
                'qrcode_path' => 'qrcode_pathてすと',
                'created_at' => '2021/01/01 11:11:11'
            ],
            [
                'name' => 'コピー用紙（500枚入り）',
                'category_id' => 2,
                'image_path1' => 'sample1.jpg',
                'image_path2' => 'sample4.jpg',
                'image_path3' => 'sample5.jpg',
                'stocks' => 2,
                'minimum_stock' => 1,
                'usage_status' => '使用中',
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_category' => '購入',
                'where_to_buy' => 'Amazon',
                'price' => '900',
                'product_number' => '',
                'manufacturer' => '',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'inspection_schedule' => null,
                'disposal_schedule' => null,
                'remarks' => '',
                'qrcode_path' => 'qrcode_pathてすと',
                'created_at' => '2021/01/01 11:11:11'
            ],
            [
                'name' => 'ゴミ袋45L(100枚入り)',
                'category_id' => 2,
                'image_path1' => 'sample1.jpg',
                'image_path2' => 'sample4.jpg',
                'image_path3' => 'sample5.jpg',
                'stocks' => '2',
                'minimum_stock' => '1',
                'usage_status' => '使用中',
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_category' => '購入',
                'where_to_buy' => 'Amazon',
                'price' => '1100',
                'product_number' => '8001',
                'manufacturer' => '',
                'date_of_acquisition' => '2023/06/01 11:11:11',
                'inspection_schedule' => null,
                'disposal_schedule' => null,
                'remarks' => '',
                'qrcode_path' => 'qrcode_pathてすと',
                'created_at' => '2021/01/01 11:11:11'
            ],
            [
                'name' => 'クイックルワイパー',
                'category_id' => 2,
                'image_path1' => 'sample1.jpg',
                'image_path2' => 'sample4.jpg',
                'image_path3' => 'sample5.jpg',
                'stocks' => '2',
                'minimum_stock' => '1',
                'usage_status' => '使用中',
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_category' => '購入',
                'where_to_buy' => 'Amazon',
                'price' => '1100',
                'product_number' => '8001',
                'manufacturer' => '',
                'date_of_acquisition' => '2023/06/01 11:11:11',
                'inspection_schedule' => null,
                'disposal_schedule' => null,
                'remarks' => '',
                'qrcode_path' => 'qrcode_pathてすと',
                'created_at' => '2021/01/01 11:11:11'
            ],
            [
                'name' => 'ノートパソコン',
                'category_id' => 3,
                'image_path1' => 'sample2.jpg',
                'image_path2' => 'sample6.jpg',
                'image_path3' => 'sample7.jpg',
                'stocks' => '1',
                'minimum_stock' => null,
                'usage_status' => '使用中',
                'end_user' => '伊地知',
                'location_of_use_id' => 1,
                'storage_location_id' => 11,
                'acquisition_category' => '購入',
                'where_to_buy' => 'Amazon',
                'price' => '30000',
                'manufacturer' => 'HP',
                'product_number' => 'HP Spectre Folio - 13-ak0001na, 6H8W2PA#ACJ',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'inspection_schedule' => null,
                'disposal_schedule' => null,
                'remarks' => '',
                'qrcode_path' => 'qrcode_pathてすと',
                'created_at' => '2021/01/01 11:11:11'
            ],
            [
                'name' => 'オフィス机',
                'category_id' => 8,
                'image_path1' => 'sample3.jpg',
                'image_path2' => 'sample8.jpg',
                'image_path3' => 'sample9.jpg',
                'stocks' => '5',
                'minimum_stock' => null,
                'usage_status' => '使用中',
                'end_user' => '山田',
                'location_of_use_id' => 2,
                'storage_location_id' => 11,
                'acquisition_category' => '購入',
                'where_to_buy' => '楽天',
                'price' => '10000',
                'manufacturer' => 'ニトリ',
                'product_number' => '5001',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'inspection_schedule' => null,
                'disposal_schedule' => null,
                'remarks' => 'あいうえおさしすせそたちつてと',
                'qrcode_path' => 'qrcode_pathてすと',
                'created_at' => '2021/01/01 11:11:11'
            ],
            [
                'name' => '避難はしご',
                'category_id' => 6,
                'image_path1' => 'sample3.jpg',
                'image_path2' => 'sample8.jpg',
                'image_path3' => 'sample9.jpg',
                'stocks' => '1',
                'minimum_stock' => null,
                'usage_status' => '未使用',
                'end_user' => '鈴木',
                'location_of_use_id' => 2,
                'storage_location_id' => 2,
                'acquisition_category' => '購入',
                'where_to_buy' => 'Amazon',
                'price' => '150000',
                'manufacturer' => 'オリロー株式会社',
                'product_number' => '',
                'date_of_acquisition' => '2023/06/01 11:11:11',
                'inspection_schedule' => null,
                'disposal_schedule' => null,
                'remarks' => '防災用に購入',
                'qrcode_path' => 'qrcode_pathテスト',
                'created_at' => '2023/06/01 11:11:11'
            ],
            [
                'name' => '消火器',
                'category_id' => 6,
                'image_path1' => 'sample3.jpg',
                'image_path2' => 'sample8.jpg',
                'image_path3' => 'sample9.jpg',
                'stocks' => '1',
                'minimum_stock' => null,
                'usage_status' => '未使用',
                'end_user' => '後藤',
                'location_of_use_id' => 4,
                'storage_location_id' => 4,
                'acquisition_category' => '購入',
                'where_to_buy' => 'Amazon',
                'price' => '11000',
                'manufacturer' => 'ヤマトプロテック株式会社',
                'product_number' => '',
                'date_of_acquisition' => '2023/06/01 11:11:11',
                'inspection_schedule' => null,
                'disposal_schedule' => null,
                'remarks' => '防災用に購入',
                'qrcode_path' => 'qrcode_pathテスト',
                'created_at' => '2023/06/01 11:11:11'
            ],
            [
                'name' => '防災用飲料水',
                'category_id' => 6,
                'image_path1' => 'sample3.jpg',
                'image_path2' => 'sample8.jpg',
                'image_path3' => 'sample9.jpg',
                'stocks' => '1',
                'minimum_stock' => null,
                'usage_status' => '使用中',
                'end_user' => '後藤',
                'location_of_use_id' => 4,
                'storage_location_id' => 4,
                'acquisition_category' => '購入',
                'where_to_buy' => 'Amazon',
                'price' => '11000',
                'manufacturer' => '',
                'product_number' => '',
                'date_of_acquisition' => '2023/06/01 11:11:11',
                'inspection_schedule' => null,
                'disposal_schedule' => '2025/07/01 00:00:00',
                'remarks' => '防災用に購入',
                'qrcode_path' => 'qrcode_pathテスト',
                'created_at' => '2023/06/01 11:11:11'
            ],
            [
                'name' => 'ブラザー プリンター A3インクジェット複合機',
                'category_id' => 3,
                'image_path1' => 'sample3.jpg',
                'image_path2' => 'sample8.jpg',
                'image_path3' => 'sample9.jpg',
                'stocks' => '1',
                'minimum_stock' => null,
                'usage_status' => '使用中',
                'end_user' => '後藤',
                'location_of_use_id' => 11,
                'storage_location_id' => 11,
                'acquisition_category' => '購入',
                'where_to_buy' => 'Amazon',
                'price' => '37000',
                'manufacturer' => 'ブラザー',
                'product_number' => '',
                'date_of_acquisition' => '2023/06/01 11:11:11',
                'inspection_schedule' => null,
                'disposal_schedule' => null,
                'remarks' => '',
                'qrcode_path' => 'qrcode_pathテスト',
                'created_at' => '2023/06/01 11:11:11'
            ],
            [
                'name' => 'ブラザー プリンター用インク',
                'category_id' => 2,
                'image_path1' => 'sample3.jpg',
                'image_path2' => 'sample8.jpg',
                'image_path3' => 'sample9.jpg',
                'stocks' => '2',
                'minimum_stock' => '1',
                'usage_status' => '使用中',
                'end_user' => '後藤',
                'location_of_use_id' => 4,
                'storage_location_id' => 4,
                'acquisition_category' => '購入',
                'where_to_buy' => 'Amazon',
                'price' => '10200',
                'manufacturer' => 'ブラザー',
                'product_number' => '',
                'date_of_acquisition' => '2023/06/01 11:11:11',
                'inspection_schedule' => null,
                'disposal_schedule' => null,
                'remarks' => '余裕を持ち予備を買っておく',
                'qrcode_path' => 'qrcode_pathテスト',
                'created_at' => '2023/06/01 11:11:11'
            ],
            [
                'name' => 'シュレッダー',
                'category_id' => 5,
                'image_path1' => 'sample3.jpg',
                'image_path2' => 'sample8.jpg',
                'image_path3' => 'sample9.jpg',
                'stocks' => '1',
                'minimum_stock' => null,
                'usage_status' => '使用中',
                'end_user' => '田中',
                'location_of_use_id' => 11,
                'storage_location_id' => 11,
                'acquisition_category' => '購入',
                'where_to_buy' => 'Amazon',
                'price' => '25000',
                'manufacturer' => 'アイリスオーヤマ',
                'product_number' => '',
                'date_of_acquisition' => '2023/06/01 11:11:11',
                'inspection_schedule' => null,
                'disposal_schedule' => null,
                'remarks' => 'ホチキス対応',
                'qrcode_path' => 'qrcode_pathテスト',
                'created_at' => '2023/06/01 11:11:11'
            ],
            [
                'name' => 'ボールペンJETSTREAM 0.5',
                'category_id' => 2,
                'image_path1' => 'sample3.jpg',
                'image_path2' => 'sample8.jpg',
                'image_path3' => 'sample9.jpg',
                'stocks' => '10',
                'minimum_stock' => '3',
                'usage_status' => '使用中',
                'end_user' => '後藤',
                'location_of_use_id' => 4,
                'storage_location_id' => 4,
                'acquisition_category' => '購入',
                'where_to_buy' => 'Amazon',
                'price' => '11000',
                'manufacturer' => '三菱',
                'product_number' => '',
                'date_of_acquisition' => '2023/06/01 11:11:11',
                'inspection_schedule' => null,
                'disposal_schedule' => null,
                'remarks' => '',
                'qrcode_path' => 'qrcode_pathテスト',
                'created_at' => '2023/06/01 11:11:11'
            ],
        ]);
    }
}
