<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Category;
use Carbon\Carbon;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $startDate = Carbon::create(2023, 4, 1, 8, 0, 0);
        $endDate = Carbon::create(2024, 7, 31, 18, 0, 0);

        DB::table('items')->insert([
            [
                'name' => 'ペーパータオル',
                'management_id' => 'CO-1000',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル2',
                'management_id' => 'CO-1002',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル3',
                'management_id' => 'CO-1003',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル',
                'management_id' => 'CO-1000',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル2',
                'management_id' => 'CO-1002',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル3',
                'management_id' => 'CO-1003',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル',
                'management_id' => 'CO-1000',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル2',
                'management_id' => 'CO-1002',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル3',
                'management_id' => 'CO-1003',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル',
                'management_id' => 'CO-1000',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル2',
                'management_id' => 'CO-1002',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル3',
                'management_id' => 'CO-1003',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル',
                'management_id' => 'CO-1000',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル2',
                'management_id' => 'CO-1002',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル3',
                'management_id' => 'CO-1003',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル',
                'management_id' => 'CO-1000',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル2',
                'management_id' => 'CO-1002',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル3',
                'management_id' => 'CO-1003',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル',
                'management_id' => 'CO-1000',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル2',
                'management_id' => 'CO-1002',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル3',
                'management_id' => 'CO-1003',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル',
                'management_id' => 'CO-1000',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル2',
                'management_id' => 'CO-1002',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
            [
                'name' => 'ペーパータオル3',
                'management_id' => 'CO-1003',
                'category_id' => 2,
                'image1' => 'sample1.jpg',
                'stock' => '10',
                'unit_id' => '3',
                'minimum_stock' => '2',
                'notification' => true,
                'usage_status_id' => 1,
                'end_user' => '',
                'location_of_use_id' => 4,
                'storage_location_id' => 11,
                'acquisition_method_id' => 1,
                'acquisition_source' => 'Amazon',
                'price' => '500',
                'date_of_acquisition' => '2021/01/01 11:11:11',
                'manufacturer' => 'エリエール',
                'product_number' => '',
                'remarks' => '',
                'qrcode' => 'qrcode_pathてすと',
                'created_at' => $this->randomDateTime($startDate, $endDate)
            ],
        ]);
    }

    private function randomDateTime($startDate, $endDate)
    {
        $randomTimestamp = rand($startDate->timestamp, $endDate->timestamp);
        $randomDateTime = Carbon::createFromTimestamp($randomTimestamp);

        // 時間を8:00～18:00の範囲に設定
        $randomHour = rand(8, 18);
        $randomDateTime->setTime($randomHour, rand(0, 59), rand(0, 59));

        return $randomDateTime;
    }

}
