<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StockTransactionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('stock_transactions')->insert([
            [
                'id'               => 1,
                'item_id'          => 50,
                'transaction_type' => '登録',
                'quantity'         => 5,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:07:00'),
            ],
            [
                'id'               => 2,
                'item_id'          => 51,
                'transaction_type' => '登録',
                'quantity'         => 2,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id'               => 3,
                'item_id'          => 52,
                'transaction_type' => '登録',
                'quantity'         => 20,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id'               => 4,
                'item_id'          => 53,
                'transaction_type' => '登録',
                'quantity'         => 4,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id'               => 5,
                'item_id'          => 54,
                'transaction_type' => '登録',
                'quantity'         => 4,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id'               => 6,
                'item_id'          => 55,
                'transaction_type' => '登録',
                'quantity'         => 4,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id'               => 7,
                'item_id'          => 56,
                'transaction_type' => '登録',
                'quantity'         => 4,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id'               => 8,
                'item_id'          => 57,
                'transaction_type' => '登録',
                'quantity'         => 5,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id'               => 9,
                'item_id'          => 58,
                'transaction_type' => '登録',
                'quantity'         => 2,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id'               => 10,
                'item_id'          => 59,
                'transaction_type' => '登録',
                'quantity'         => 2,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id'               => 11,
                'item_id'          => 60,
                'transaction_type' => '登録',
                'quantity'         => 2,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:08:00'),
            ],
            [
                'id'               => 12,
                'item_id'          => 61,
                'transaction_type' => '登録',
                'quantity'         => 2,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id'               => 13,
                'item_id'          => 62,
                'transaction_type' => '登録',
                'quantity'         => 20,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id'               => 14,
                'item_id'          => 63,
                'transaction_type' => '登録',
                'quantity'         => 10,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id'               => 15,
                'item_id'          => 64,
                'transaction_type' => '登録',
                'quantity'         => 12,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id'               => 16,
                'item_id'          => 65,
                'transaction_type' => '登録',
                'quantity'         => 4,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id'               => 17,
                'item_id'          => 66,
                'transaction_type' => '登録',
                'quantity'         => 2,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id'               => 18,
                'item_id'          => 67,
                'transaction_type' => '登録',
                'quantity'         => 50,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id'               => 19,
                'item_id'          => 68,
                'transaction_type' => '登録',
                'quantity'         => 100,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id'               => 20,
                'item_id'          => 69,
                'transaction_type' => '登録',
                'quantity'         => 10,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id'               => 21,
                'item_id'          => 70,
                'transaction_type' => '登録',
                'quantity'         => 20,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:09:00'),
            ],
            [
                'id'               => 22,
                'item_id'          => 71,
                'transaction_type' => '登録',
                'quantity'         => 5,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
            ],
            [
                'id'               => 23,
                'item_id'          => 72,
                'transaction_type' => '登録',
                'quantity'         => 180,
                'operator_name'    => '管理者大川',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/01 15:10:00'),
            ],
            [
                'id'               => 24,
                'item_id'          => 50,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '鈴木',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 9:14:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 9:14:00'),
            ],
            [
                'id'               => 25,
                'item_id'          => 51,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '田中',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 10:33:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 10:33:00'),
            ],
            [
                'id'               => 26,
                'item_id'          => 52,
                'transaction_type' => '出庫',
                'quantity'         => -4,
                'operator_name'    => '井上',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/01 14:41:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/01 14:41:00'),
            ],
            [
                'id'               => 27,
                'item_id'          => 53,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '中村',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/11 11:04:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/11 11:04:00'),
            ],
            [
                'id'               => 28,
                'item_id'          => 57,
                'transaction_type' => '入庫',
                'quantity'         => 3,
                'operator_name'    => '小林',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/10 8:23:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/10 8:23:00'),
            ],
            [
                'id'               => 29,
                'item_id'          => 57,
                'transaction_type' => '出庫',
                'quantity'         => -2,
                'operator_name'    => '鈴木',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/25 15:12:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/25 15:12:00'),
            ],
            [
                'id'               => 30,
                'item_id'          => 57,
                'transaction_type' => '入庫',
                'quantity'         => 8,
                'operator_name'    => '田中',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/08 9:48:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/08 9:48:00'),
            ],
            [
                'id'               => 31,
                'item_id'          => 58,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '井上',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 13:27:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 13:27:00'),
            ],
            [
                'id'               => 32,
                'item_id'          => 58,
                'transaction_type' => '入庫',
                'quantity'         => 2,
                'operator_name'    => '中村',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/18 11:36:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/18 11:36:00'),
            ],
            [
                'id'               => 33,
                'item_id'          => 58,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '小林',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 8:57:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 8:57:00'),
            ],
            [
                'id'               => 34,
                'item_id'          => 59,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '鈴木',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/11 10:11:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/11 10:11:00'),
            ],
            [
                'id'               => 35,
                'item_id'          => 59,
                'transaction_type' => '入庫',
                'quantity'         => 1,
                'operator_name'    => '田中',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/13 14:03:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/13 14:03:00'),
            ],
            [
                'id'               => 36,
                'item_id'          => 62,
                'transaction_type' => '出庫',
                'quantity'         => -4,
                'operator_name'    => '井上',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/20 16:43:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/20 16:43:00'),
            ],
            [
                'id'               => 37,
                'item_id'          => 62,
                'transaction_type' => '出庫',
                'quantity'         => -6,
                'operator_name'    => '中村',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/11 9:18:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/11 9:18:00'),
            ],
            [
                'id'               => 38,
                'item_id'          => 63,
                'transaction_type' => '出庫',
                'quantity'         => -4,
                'operator_name'    => '小林',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/02 10:04:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/02 10:04:00'),
            ],
            [
                'id'               => 39,
                'item_id'          => 64,
                'transaction_type' => '出庫',
                'quantity'         => -4,
                'operator_name'    => '鈴木',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/10 14:31:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/10 14:31:00'),
            ],
            [
                'id'               => 40,
                'item_id'          => 64,
                'transaction_type' => '出庫',
                'quantity'         => -4,
                'operator_name'    => '田中',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 8:42:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 8:42:00'),
            ],
            [
                'id'               => 41,
                'item_id'          => 64,
                'transaction_type' => '入庫',
                'quantity'         => 16,
                'operator_name'    => '井上',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/22 11:56:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/22 11:56:00'),
            ],
            [
                'id'               => 42,
                'item_id'          => 64,
                'transaction_type' => '出庫',
                'quantity'         => -3,
                'operator_name'    => '中村',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/02 12:11:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/02 12:11:00'),
            ],
            [
                'id'               => 43,
                'item_id'          => 64,
                'transaction_type' => '出庫',
                'quantity'         => -10,
                'operator_name'    => '小林',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/15 13:22:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/15 13:22:00'),
            ],
            [
                'id'               => 44,
                'item_id'          => 65,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '鈴木',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 14:02:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 14:02:00'),
            ],
            [
                'id'               => 45,
                'item_id'          => 65,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '田中',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/09 10:46:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/09 10:46:00'),
            ],
            [
                'id'               => 46,
                'item_id'          => 65,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '井上',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/26 15:29:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/26 15:29:00'),
            ],
            [
                'id'               => 47,
                'item_id'          => 65,
                'transaction_type' => '入庫',
                'quantity'         => 4,
                'operator_name'    => '中村',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/28 13:11:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/28 13:11:00'),
            ],
            [
                'id'               => 48,
                'item_id'          => 66,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '小林',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/30 9:03:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/30 9:03:00'),
            ],
            [
                'id'               => 49,
                'item_id'          => 66,
                'transaction_type' => '入庫',
                'quantity'         => 2,
                'operator_name'    => '鈴木',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/01 8:29:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/01 8:29:00'),
            ],
            [
                'id'               => 50,
                'item_id'          => 66,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '田中',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/29 12:46:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/29 12:46:00'),
            ],
            [
                'id'               => 51,
                'item_id'          => 67,
                'transaction_type' => '出庫',
                'quantity'         => -10,
                'operator_name'    => '井上',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 11:17:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 11:17:00'),
            ],
            [
                'id'               => 52,
                'item_id'          => 67,
                'transaction_type' => '出庫',
                'quantity'         => -10,
                'operator_name'    => '中村',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/11 14:11:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/11 14:11:00'),
            ],
            [
                'id'               => 53,
                'item_id'          => 67,
                'transaction_type' => '出庫',
                'quantity'         => -10,
                'operator_name'    => '小林',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/29 8:51:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/29 8:51:00'),
            ],
            [
                'id'               => 54,
                'item_id'          => 68,
                'transaction_type' => '出庫',
                'quantity'         => -5,
                'operator_name'    => '鈴木',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/10 8:02:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/10 8:02:00'),
            ],
            [
                'id'               => 55,
                'item_id'          => 68,
                'transaction_type' => '出庫',
                'quantity'         => -5,
                'operator_name'    => '田中',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 12:02:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 12:02:00'),
            ],
            [
                'id'               => 56,
                'item_id'          => 68,
                'transaction_type' => '出庫',
                'quantity'         => -5,
                'operator_name'    => '井上',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/30 16:03:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/30 16:03:00'),
            ],
            [
                'id'               => 57,
                'item_id'          => 68,
                'transaction_type' => '出庫',
                'quantity'         => -5,
                'operator_name'    => '中村',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/11 13:03:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/11 13:03:00'),
            ],
            [
                'id'               => 58,
                'item_id'          => 69,
                'transaction_type' => '出庫',
                'quantity'         => -5,
                'operator_name'    => '小林',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/08 15:48:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/08 15:48:00'),
            ],
            [
                'id'               => 59,
                'item_id'          => 69,
                'transaction_type' => '入庫',
                'quantity'         => 30,
                'operator_name'    => '鈴木',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/11 9:12:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/11 9:12:00'),
            ],
            [
                'id'               => 60,
                'item_id'          => 69,
                'transaction_type' => '出庫',
                'quantity'         => -5,
                'operator_name'    => '田中',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 11:01:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 11:01:00'),
            ],
            [
                'id'               => 61,
                'item_id'          => 69,
                'transaction_type' => '出庫',
                'quantity'         => -6,
                'operator_name'    => '井上',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/22 13:31:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/22 13:31:00'),
            ],
            [
                'id'               => 62,
                'item_id'          => 69,
                'transaction_type' => '出庫',
                'quantity'         => -5,
                'operator_name'    => '中村',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/29 8:52:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/29 8:52:00'),
            ],
            [
                'id'               => 63,
                'item_id'          => 69,
                'transaction_type' => '出庫',
                'quantity'         => -6,
                'operator_name'    => '小林',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 12:08:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 12:08:00'),
            ],
            [
                'id'               => 64,
                'item_id'          => 69,
                'transaction_type' => '出庫',
                'quantity'         => -6,
                'operator_name'    => '鈴木',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/12 9:37:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/12 9:37:00'),
            ],
            [
                'id'               => 65,
                'item_id'          => 69,
                'transaction_type' => '入庫',
                'quantity'         => 30,
                'operator_name'    => '田中',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/20 8:29:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/20 8:29:00'),
            ],
            [
                'id'               => 66,
                'item_id'          => 69,
                'transaction_type' => '出庫',
                'quantity'         => -5,
                'operator_name'    => '井上',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/27 15:21:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/27 15:21:00'),
            ],
            [
                'id'               => 67,
                'item_id'          => 70,
                'transaction_type' => '出庫',
                'quantity'         => -3,
                'operator_name'    => '中村',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/07 10:02:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/07 10:02:00'),
            ],
            [
                'id'               => 68,
                'item_id'          => 70,
                'transaction_type' => '出庫',
                'quantity'         => -4,
                'operator_name'    => '小林',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 8:34:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 8:34:00'),
            ],
            [
                'id'               => 69,
                'item_id'          => 70,
                'transaction_type' => '出庫',
                'quantity'         => -3,
                'operator_name'    => '鈴木',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 12:44:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 12:44:00'),
            ],
            [
                'id'               => 70,
                'item_id'          => 70,
                'transaction_type' => '出庫',
                'quantity'         => -4,
                'operator_name'    => '田中',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/28 14:12:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/28 14:12:00'),
            ],
            [
                'id'               => 71,
                'item_id'          => 70,
                'transaction_type' => '出庫',
                'quantity'         => -3,
                'operator_name'    => '井上',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 16:47:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 16:47:00'),
            ],
            [
                'id'               => 72,
                'item_id'          => 70,
                'transaction_type' => '入庫',
                'quantity'         => 27,
                'operator_name'    => '中村',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/08 15:32:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/08 15:32:00'),
            ],
            [
                'id'               => 73,
                'item_id'          => 70,
                'transaction_type' => '出庫',
                'quantity'         => -3,
                'operator_name'    => '小林',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/15 11:19:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/15 11:19:00'),
            ],
            [
                'id'               => 74,
                'item_id'          => 70,
                'transaction_type' => '出庫',
                'quantity'         => -3,
                'operator_name'    => '鈴木',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/22 10:12:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/22 10:12:00'),
            ],
            [
                'id'               => 75,
                'item_id'          => 70,
                'transaction_type' => '出庫',
                'quantity'         => -3,
                'operator_name'    => '田中',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/29 9:08:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/29 9:08:00'),
            ],
            [
                'id'               => 76,
                'item_id'          => 71,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '井上',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 13:01:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 13:01:00'),
            ],
            [
                'id'               => 77,
                'item_id'          => 71,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '中村',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/30 15:41:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/30 15:41:00'),
            ],
            [
                'id'               => 78,
                'item_id'          => 71,
                'transaction_type' => '入庫',
                'quantity'         => 5,
                'operator_name'    => '小林',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/01 8:22:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/01 8:22:00'),
            ],
            [
                'id'               => 79,
                'item_id'          => 71,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '鈴木',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/15 10:02:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/15 10:02:00'),
            ],
            [
                'id'               => 80,
                'item_id'          => 71,
                'transaction_type' => '出庫',
                'quantity'         => -1,
                'operator_name'    => '田中',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/29 11:31:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/29 11:31:00'),
            ],
            [
                'id'               => 81,
                'item_id'          => 72,
                'transaction_type' => '出庫',
                'quantity'         => -40,
                'operator_name'    => '井上',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/07 13:52:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/07 13:52:00'),
            ],
            [
                'id'               => 82,
                'item_id'          => 72,
                'transaction_type' => '出庫',
                'quantity'         => -40,
                'operator_name'    => '中村',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 9:21:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/15 9:21:00'),
            ],
            [
                'id'               => 83,
                'item_id'          => 72,
                'transaction_type' => '出庫',
                'quantity'         => -40,
                'operator_name'    => '小林',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 8:13:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/21 8:13:00'),
            ],
            [
                'id'               => 84,
                'item_id'          => 72,
                'transaction_type' => '出庫',
                'quantity'         => -40,
                'operator_name'    => '鈴木',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/28 11:37:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/28 11:37:00'),
            ],
            [
                'id'               => 85,
                'item_id'          => 72,
                'transaction_type' => '入庫',
                'quantity'         => 200,
                'operator_name'    => '田中',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/30 16:23:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/10/30 16:23:00'),
            ],
            [
                'id'               => 86,
                'item_id'          => 72,
                'transaction_type' => '出庫',
                'quantity'         => -40,
                'operator_name'    => '井上',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 12:51:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/05 12:51:00'),
            ],
            [
                'id'               => 87,
                'item_id'          => 72,
                'transaction_type' => '出庫',
                'quantity'         => -40,
                'operator_name'    => '中村',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/12 8:56:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/12 8:56:00'),
            ],
            [
                'id'               => 88,
                'item_id'          => 72,
                'transaction_type' => '出庫',
                'quantity'         => -40,
                'operator_name'    => '小林',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/19 14:41:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/19 14:41:00'),
            ],
            [
                'id'               => 89,
                'item_id'          => 72,
                'transaction_type' => '出庫',
                'quantity'         => -40,
                'operator_name'    => '鈴木',
                'created_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/26 13:12:00'),
                'updated_at'       => Carbon::createFromFormat('Y/m/d H:i:s', '2024/11/26 13:12:00'),
            ],
        ]);
    }
}
